name:                Onitama
version:             0.1.0.0
github:              "JonHarder/Onitama"
license:             BSD3
author:              "Jon Harder"
maintainer:          "example@example.com"
copyright:           "2020 Jonathan Harder"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JonHarder/Onitama#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  Onitama:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Onitama

tests:
  Onitama-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Onitama
